return {
  "petertriho/nvim-scrollbar",
  event = "VeryLazy",
  dependencies = { "lewis6991/gitsigns.nvim" },
  config = function()
    require("scrollbar").setup({
      show = true,
      show_in_active_only = false,
      set_highlights = true,
      folds = 1000,
      max_lines = false,
      hide_if_all_visible = false,
      throttle_ms = 100,
      handle = {
        text = " ",
        blend = 30,
        color = "#6c7086",
        color_nr = 240,
        highlight = "CursorColumn",
        hide_if_all_visible = true,
      },
      marks = {
        Cursor = { text = "•", priority = 0, color = "#f38ba8" },
        Search = { text = { "-", "=" }, priority = 1, color = "#f9e2af" },
        Error = { text = { "-", "=" }, priority = 2, color = "#f38ba8" },
        Warn = { text = { "-", "=" }, priority = 3, color = "#f9e2af" },
        Info = { text = { "-", "=" }, priority = 4, color = "#89b4fa" },
        Hint = { text = { "-", "=" }, priority = 5, color = "#a6e3a1" },
        Misc = { text = { "-", "=" }, priority = 6, color = "#cba6f7" },
        GitAdd = { text = "┃", priority = 7, color = "#a6e3a1" },
        GitChange = { text = "┃", priority = 7, color = "#f9e2af" },
        GitDelete = { text = "▁", priority = 7, color = "#f38ba8" },
      },
      excluded_filetypes = {
        "cmp_docs",
        "cmp_menu",
        "noice",
        "prompt",
        "TelescopePrompt",
        "aerial",
        "alpha",
        "dashboard",
        "lazy",
        "mason",
        "neo-tree",
        "neotest-summary",
        "notify",
        "toggleterm",
      },
      autocmd = {
        render = {
          "BufWinEnter",
          "TabEnter",
          "TermEnter",
          "WinEnter",
          "CmdwinLeave",
          "TextChanged",
          "VimResized",
          "WinScrolled",
        },
        clear = {
          "BufWinLeave",
          "TabLeave",
          "TermLeave",
          "WinLeave",
        },
      },
      handlers = {
        cursor = true,
        diagnostic = true,
        gitsigns = true,
        handle = true,
        search = false,
        ale = false,
      },
    })
    require("scrollbar.handlers.gitsigns").setup()
  end,
}