return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  config = function()
    local wk = require("which-key")
    wk.setup({
      delay = 100,
      plugins = {
        spelling = { enabled = false },
        presets = {
          operators = false,
          motions = false,
          text_objects = false,
          windows = false,
          nav = false,
        },
      },
      hidden = { "v", "V", "<C-v>" },
    })
    wk.add({
      { "<leader>e", desc = "File Explorer" },
      { "<leader>f", desc = "Find Files" },
      { "<leader>b", desc = "Buffers" },
      { "<leader>w", desc = "Save" },
      { "<leader>q", desc = "Quit" },
      { "<leader>h", desc = "No Highlight" },
      { "<leader>x", desc = "Close Buffer" },
      { "<leader>o", desc = "Symbol Outline" },
      { "<leader>O", desc = "Aerial Nav" },
      { "<leader>g", group = "Git" },
      { "<leader>gg", desc = "Neogit Status" },
      { "<leader>gd", desc = "Diff View" },
      { "<leader>gh", desc = "Git History" },
      { "<leader>gs", desc = "Live Grep" },
      { "<leader>s", group = "Search/Replace" },
      { "<leader>sr", desc = "Search & Replace (project)" },
      { "<leader>sR", desc = "Search & Replace (file/selection)" },
      { "<leader>st", desc = "Search TODOs" },
      { "<leader>r", group = "Rename" },
      { "<leader>rn", desc = "Rename Symbol" },
      { "<leader>c", group = "Code" },
      { "<leader>ca", desc = "Code Action" },
      { "<leader>cl", desc = "LSP References" },
      { "<leader>cs", desc = "Symbols" },
      { "<leader>d", group = "Document" },
      { "<leader>ds", desc = "Document Symbols" },
      { "<leader>D", desc = "Type Definition" },
      { "<leader>p", group = "Preview" },
      { "<leader>x", group = "Trouble" },
      { "<leader>xx", desc = "Diagnostics" },
      { "<leader>xX", desc = "Buffer Diagnostics" },
      { "<leader>xL", desc = "Location List" },
      { "<leader>xQ", desc = "Quickfix List" },
      { "<leader>xt", desc = "Todo (Trouble)" },
      { "<leader>xT", desc = "Todo/Fix/Fixme (Trouble)" },
      { "g", group = "Go" },
      { "gd", desc = "Go to Definition" },
      { "gD", desc = "Go to Declaration" },
      { "gr", desc = "References" },
      { "gi", desc = "Go to Implementation" },
      { "gh", desc = "Start of Line" },
      { "gl", desc = "End of Line" },
      { "s", group = "Flash" },
      { "S", desc = "Flash Treesitter" },
      { "[", group = "Previous" },
      { "]", group = "Next" },
      { "]", "t", desc = "Next TODO" },
      { "[", "t", desc = "Previous TODO" },
    })
  end,
}
