return {
  "folke/which-key.nvim",
  event = "UIEnter",
  config = function()
    local wk = require("which-key")
    wk.setup({
      delay = 100,
      plugins = {
        spelling = { enabled = false },
      },
    })
    wk.add({
      { "<leader>e", desc = "File Explorer" },
      { "<leader>f", desc = "Find Files" },
      { "<leader>/", desc = "Live Grep" },
      { "<leader>w", desc = "Save" },
      { "<leader>q", desc = "Quit" },
      { "<leader>h", desc = "No Highlight" },
      { "<leader>P", desc = "Open PDF (Sumatra)" },
      { "<leader>T", desc = "Toggle Terminal (bottom)" },
      { "<leader>o", desc = "Symbol Outline" },
      { "<leader>O", desc = "Aerial Nav" },
      { "<leader>j", desc = "Move line/selection down" },
      { "<leader>k", desc = "Move line/selection up" },
      { "<leader>b", group = "Buffer" },
      { "<leader>bb", desc = "List Buffers" },
      { "<leader>bd", desc = "Close Buffer" },
      { "<leader>1", desc = "Buffer 1" },
      { "<leader>2", desc = "Buffer 2" },
      { "<leader>3", desc = "Buffer 3" },
      { "<leader>4", desc = "Buffer 4" },
      { "<leader>5", desc = "Buffer 5" },
      { "<leader>g", group = "Git" },
      { "<leader>gs", desc = "Git Status" },
      { "<leader>gg", desc = "Neogit" },
      { "<leader>gd", desc = "Diff View" },
      { "<leader>gh", desc = "Git History" },
      { "<leader>gp", desc = "Preview Hunk" },
      { "<leader>gb", desc = "Blame Line" },
      { "<leader>gr", desc = "Reset Hunk" },
      { "<leader>s", group = "Search/Replace" },
      { "<leader>sr", desc = "Search & Replace (project)" },
      { "<leader>sR", desc = "Search & Replace (file/selection)" },
      { "<leader>st", desc = "Search TODOs" },
      { "<leader>r", group = "Rename/Refactor" },
      { "<leader>rn", desc = "Rename Symbol" },
      { "<leader>c", group = "Code" },
      { "<leader>ca", desc = "Code Action" },
      { "<leader>cl", desc = "LSP References" },
      { "<leader>cs", desc = "Symbols" },
      { "<leader>d", group = "Document" },
      { "<leader>ds", desc = "Document Symbols" },
      { "<leader>D", desc = "Type Definition" },
      { "<leader>n", group = "Next (swap)" },
      { "<leader>na", desc = "Swap parameter next" },
      { "<leader>pa", desc = "Swap parameter previous" },
      { "<leader>x", group = "Trouble" },
      { "<leader>xx", desc = "Diagnostics" },
      { "<leader>xX", desc = "Buffer Diagnostics" },
      { "<leader>xL", desc = "Location List" },
      { "<leader>xQ", desc = "Quickfix List" },
      { "<leader>xt", desc = "Todo (Trouble)" },
      { "<leader>xT", desc = "Todo/Fix/Fixme (Trouble)" },
      { "<leader>a", group = "AI (Avante)" },
      { "<leader>aa", desc = "Ask" },
      { "<leader>ae", desc = "Edit" },
      { "<leader>ar", desc = "Refresh" },
      { "g", group = "Go" },
      { "gd", desc = "Go to Definition" },
      { "gD", desc = "Go to Declaration" },
      { "gr", desc = "References" },
      { "gi", desc = "Go to Implementation" },
      { "gh", desc = "Start of Line" },
      { "gl", desc = "End of Line" },
      { "s", desc = "Flash" },
      { "S", desc = "Flash Treesitter" },
      { "[", group = "Previous" },
      { "]", group = "Next" },
    })
  end,
}
